import Head from "next/head"
import Script from "next/script"
import NavBar from './Components/NavBar';


const contact = () => {
  return (
     <>
     <Head>
     <title>MySelf - Contact</title>
     <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/favicon.ico" />
   </Head>
   <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>
   <NavBar />
   <div className="container">
   <h3 className="text-center">Contact Us </h3>
   <div className="mb-3">
   <label htmlFor="exampleFormControlInput1" className="form-label">Name</label>
   <input type="email" className="form-control" id="exampleFormControlInput1" placeholder="Enter Your Name" required/>
 </div>
   <div className="mb-3">
   <label htmlFor="exampleFormControlInput1" className="form-label">Email </label>
   <input type="email" className="form-control" id="exampleFormControlInput1" placeholder="Enter Your Email" required/>
 </div>
   <div className="mb-3">
   <label htmlFor="exampleFormControlInput1" className="form-label">Phone</label>
   <input type="email" className="form-control" id="exampleFormControlInput1" placeholder="Enter Your Phone" required/>
 </div>
 <div className="mb-3">
   <label htmlFor="exampleFormControlTextarea1" className="form-label">Message</label>
   <textarea className="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Enter Your Message"></textarea>
 </div>
 <button className="btn btn-primary">Submit</button>
   </div>
</>
  )
}

export default contact