import Image from 'next/image';
import Script from 'next/script';
import Head from 'next/head';
import NavBar from './Components/NavBar';


const service = () => {
  return (
    <>
    <Head>
    <title>MySelf - Service</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>
  <NavBar />
  <div className="container">
  <div className="row row-cols-1 row-cols-md-2 g-4 mt-3">
  <div className="col">
    <div className="card">
      <Image src="/images/blockchain.jpg" className="card-top" alt="BlockChain" width={1400} height={500}/>
      <div className="card-body">
        <h5 className="card-title">Block Chain</h5>
        <p className="card-text">Blockchain is a futuristic technology used in crypto mining, making smart contracts and many more, we help in building products this amazing technology.</p>
      </div>
    </div>
  </div>
  <div className="col">
    <div className="card">
      <Image src="/images/iot.jpg" className="card-top" alt="IoT" width={1400} height={500}/>
      <div className="card-body">
        <h5 className="card-title">Internet Of Things</h5>
        <p className="card-text">Internet of Things is a very vast usecase technology that is helpful in medical and engineering projects, we help in building products this amazing technology.</p>
      </div>
    </div>
  </div>
  <div className="col">
    <div className="card">
      <Image src="/images/robotics.jpg" className="card-top" alt="Robots" width={1400} height={500} />
      <div className="card-body">
        <h5 className="card-title">Robotics</h5>
        <p className="card-text">Robotics is a very broadly categorised area which is powered by smart and powerful AI robots that are very useful in many industrial and medical purposes.</p>
      </div>
    </div>
  </div>
  <div className="col">
    <div className="card">
      <Image src="/images/software.jpg" className="card-top" alt="Softare Devlopmemt" width={1400} height={500} />
      <div className="card-body">
        <h5 className="card-title">Software Devlopment</h5>
        <p className="card-text">In this modern worls services sector is booming at a very fast rate and it is the main reason that why every company need a website or a app which we build for you. </p>
      </div>
    </div>
  </div>
</div>
  </div>
</>
  );
};

export default service;
